import 'package:edudibon_flutter_bloc/admin_module/hrsm/staff_management/model/employee_entity.dart';

import '../model/employee_model.dart';

List<EmployeeModel> dummyEmployees = [
  EmployeeModel(
    name: 'Amay Pande',
    email: 'amay.pande@example.com',
    role: 'Teaching',
    mobile: '9876543210',
    address: '123, Teachers Colony, Mumbai',
    staffId: 'T101',
    profileImageUrl: 'http://example.com/images/amay_pande.jpg',
    department: 'Science',
    subDepartment: 'Physics',
    subject: 'Physics',
    adharCardNumber: '1234-5678-9012',
    pancardNumber: 'ABCDE1234F',
    documentDepartment: 'HR',
    documentImages: ['http://example.com/docs/amay_id.jpg'],
    documentLabels: ['Aadhar Card'],
    joiningDate: '2020-08-15',
    relievingDate: '',
    employeeType: 'Permanent',
    renewals: '',
    verification: 'verified',
    leaves: LeaveInfo(total: 2, sick: 2, casual: 2, remaining: 0),
    salary: SalaryInfo(ctc: 5, fixed: 2, variable: 2, benefits: 0, deduction: 0),
    bankDetails: BankDetails(bankName: "bankName", branch: "branch", accountType: "accountType", accountNumber: 1234, ifscCode: "ifscCode"),
    attendancePercent: 95.5,
  ),
  EmployeeModel(
    name: 'Amay Pande',
    email: 'amay.pande@example.com',
    role: 'Teaching',
    mobile: '9876543210',
    address: '123, Teachers Colony, Mumbai',
    staffId: 'T101',
    profileImageUrl: 'http://example.com/images/amay_pande.jpg',
    department: 'Science',
    subDepartment: 'Physics',
    subject: 'Physics',
    adharCardNumber: '1234-5678-9012',
    pancardNumber: 'ABCDE1234F',
    documentDepartment: 'HR',
    documentImages: ['http://example.com/docs/amay_id.jpg'],
    documentLabels: ['Aadhar Card'],
    joiningDate: '2020-08-15',
    relievingDate: '',
    employeeType: 'Permanent',
    renewals: '',
    verification: 'verified',
    leaves: LeaveInfo(total: 2, sick: 2, casual: 2, remaining: 0),
    salary: SalaryInfo(ctc: 5, fixed: 2, variable: 2, benefits: 0, deduction: 0),
    bankDetails: BankDetails(bankName: "bankName", branch: "branch", accountType: "accountType", accountNumber: 1234, ifscCode: "ifscCode"),
    attendancePercent: 95.5,
  ),
  EmployeeModel(
    name: 'Amay Pande',
    email: 'amay.pande@example.com',
    role: 'Teaching',
    mobile: '9876543210',
    address: '123, Teachers Colony, Mumbai',
    staffId: 'T101',
    profileImageUrl: 'http://example.com/images/amay_pande.jpg',
    department: 'Science',
    subDepartment: 'Physics',
    subject: 'Physics',
    adharCardNumber: '1234-5678-9012',
    pancardNumber: 'ABCDE1234F',
    documentDepartment: 'HR',
    documentImages: ['http://example.com/docs/amay_id.jpg'],
    documentLabels: ['Aadhar Card'],
    joiningDate: '2020-08-15',
    relievingDate: '',
    employeeType: 'Permanent',
    renewals: '',
    verification: 'verified',
    leaves: LeaveInfo(total: 2, sick: 2, casual: 2, remaining: 0),
    salary: SalaryInfo(ctc: 5, fixed: 2, variable: 2, benefits: 0, deduction: 0),
    bankDetails: BankDetails(bankName: "bankName", branch: "branch", accountType: "accountType", accountNumber: 1234, ifscCode: "ifscCode"),
    attendancePercent: 95.5,
  ),
  EmployeeModel(
    name: 'Amay Pande',
    email: 'amay.pande@example.com',
    role: 'Teaching',
    mobile: '9876543210',
    address: '123, Teachers Colony, Mumbai',
    staffId: 'T101',
    profileImageUrl: 'http://example.com/images/amay_pande.jpg',
    department: 'Science',
    subDepartment: 'Physics',
    subject: 'Physics',
    adharCardNumber: '1234-5678-9012',
    pancardNumber: 'ABCDE1234F',
    documentDepartment: 'HR',
    documentImages: ['http://example.com/docs/amay_id.jpg'],
    documentLabels: ['Aadhar Card'],
    joiningDate: '2020-08-15',
    relievingDate: '',
    employeeType: 'Permanent',
    renewals: '',
    verification: 'verified',
    leaves: LeaveInfo(total: 2, sick: 2, casual: 2, remaining: 0),
    salary: SalaryInfo(ctc: 5, fixed: 2, variable: 2, benefits: 0, deduction: 0),
    bankDetails: BankDetails(bankName: "bankName", branch: "branch", accountType: "accountType", accountNumber: 1234, ifscCode: "ifscCode"),
    attendancePercent: 95.5,
  ),
];