import 'package:edudibon_flutter_bloc/admin_module/hrsm/staff_management/model/staff_entity.dart';

class StaffFormModel extends StaffEntity {
  final String photoUrl;
  final bool isVerified;

  StaffFormModel({
    String name = '',
    String staffId = '',
    String department = '',
    String mobile = '',
    String email = '',
    String address = '',
    String adharNumber = '',
    String panNumber = '',
    String salary = '',
    String pfDeduction = '',
    String bankName = '',
    String accountNumber = '',
    String ifsc = '',
    String dateOfJoining = '',
    String relivingDate = '',
    String remarks = '',
    String academicYear = '',
    String employeeType = '',
    String education = '',
    String percentage = '',
    String verificationStatus = 'Verified',
    String emergencyMobileNumber = '',  // NEW
    this.photoUrl = '',
    this.isVerified = false,
  }) : super(
    name: name,
    staffId: staffId,
    department: department,
    mobile: mobile,
    email: email,
    address: address,
    adharNumber: adharNumber,
    panNumber: panNumber,
    salary: salary,
    pfDeduction: pfDeduction,
    bankName: bankName,
    accountNumber: accountNumber,
    ifsc: ifsc,
    dateOfJoining: dateOfJoining,
    relivingDate: relivingDate,
    remarks: remarks,
    academicYear: academicYear,
    employeeType: employeeType,
    education: education,
    percentage: percentage,
    verificationStatus: verificationStatus,
    emergencyMobileNumber: emergencyMobileNumber,  // NEW
  );

  StaffFormModel copyWith({
    String? name,
    String? staffId,
    String? department,
    String? mobile,
    String? email,
    String? address,
    String? adharNumber,
    String? panNumber,
    String? salary,
    String? pfDeduction,
    String? bankName,
    String? accountNumber,
    String? ifsc,
    String? dateOfJoining,
    String? relivingDate,
    String? remarks,
    String? academicYear,
    String? employeeType,
    String? education,
    String? percentage,
    String? verificationStatus,
    String? emergencyMobileNumber,  // NEW
    String? photoUrl,
    bool? isVerified,
  }) {
    return StaffFormModel(
      name: name ?? this.name,
      staffId: staffId ?? this.staffId,
      department: department ?? this.department,
      mobile: mobile ?? this.mobile,
      email: email ?? this.email,
      address: address ?? this.address,
      adharNumber: adharNumber ?? this.adharNumber,
      panNumber: panNumber ?? this.panNumber,
      salary: salary ?? this.salary,
      pfDeduction: pfDeduction ?? this.pfDeduction,
      bankName: bankName ?? this.bankName,
      accountNumber: accountNumber ?? this.accountNumber,
      ifsc: ifsc ?? this.ifsc,
      dateOfJoining: dateOfJoining ?? this.dateOfJoining,
      relivingDate: relivingDate ?? this.relivingDate,
      remarks: remarks ?? this.remarks,
      academicYear: academicYear ?? this.academicYear,
      employeeType: employeeType ?? this.employeeType,
      education: education ?? this.education,
      percentage: percentage ?? this.percentage,
      verificationStatus: verificationStatus ?? this.verificationStatus,
      emergencyMobileNumber: emergencyMobileNumber ?? this.emergencyMobileNumber,  // NEW
      photoUrl: photoUrl ?? this.photoUrl,
      isVerified: isVerified ?? this.isVerified,
    );
  }
}
